import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence, useScroll, useTransform } from 'motion/react';
import { Search, MapPin, Filter, Heart, Home, Trees, Map, Building2, Phone, Calendar, ArrowRight, LogOut, FileText, CheckCircle2, Clock, X, Plus, Bell, Star, Shield, MessageCircle, Mail, User, RefreshCw, Briefcase, TrendingUp, Sparkles, Tag, ChevronLeft, ChevronDown, TrendingDown, Globe, DollarSign, Eye, Users, Key, Zap, Layout, FileCheck, PenTool, Landmark, Palette, Leaf, Sun, Apple, Wind, Moon, ShoppingBag, Truck, BarChart3, Settings, CreditCard, Bot } from 'lucide-react';
import Logo from './Logo';
import { api } from '../services/api';
import { TEST_IDS } from '../constants/testIds';
import FarmLandOnboardingModal from './FarmLandOnboardingModal';
import PlotsOnboardingModal from './PlotsOnboardingModal';
import Footer from './Footer';
import { useEnquiryUpdates } from '../hooks/useNotifications';
import ClientProfileEditModal from './ClientProfileEditModal';
import ClientChatWidget from './ClientChatWidget';
import ErrorBoundary from './ErrorBoundary';
import type { AppRole } from '../hooks/useAuth';
import { getClientProfile } from '../hooks/useClientProfile';
